import pandas as pd
df=pd.read_csv('salary_data.csv')
print(df)
print(df.head(15))
print(df.head())
print(df.tail())
print(df.info())
print(df.columns)
print(df.dtypes)
print(df.describe())
print(df.describe(include='O'))
print(df.duplicated())
print(df.duplicated().sum())
print(df.isnull())
print(df.isnull().sum())
df.columns= df.columns.str.lower()
print(df.head())
print(df.values)
print(df.age)
print(df.age.describe())
print(df.age.mean())
print(df.age.mode())
print(df.age.median())
print(df.age.var())
print(df.age.std())
import matplotlib.pyplot as plt
plt.show(df.age.hist())
plt.show(plt.hist(df.age))
import seaborn as sns
plt.show(sns.histplot(df.age))
plt.show(sns.displot(df.age, kde='true'))
plt.show(sns.kdeplot(x='age', data=df))
plt.show(sns.boxplot(x='age', data=df))
plt.show(sns.boxplot(y='age', data=df))
print(df.country.describe())
print(df.country.nunique())
print(df.country.unique())
print(df.country.value_counts())
plt.show(df.country.value_counts().plot(kind='bar'))
country_count = df.country.value_counts().reset_index()
print(country_count)

